In [1]:
import numpy as np
import pandas as pd
import pyomo.environ as pyo
import importlib.resources
import sys
import os
import json
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..')))
from Customized_Determinstic_PT.utils import read_gmlc_gen
import matplotlib.pyplot as plt

# RTS GMLC

## Read gen.csv

In [13]:
# path for the generators
csv_path = os.path.join(os.getcwd(), '..', 'Data', 'gen.csv')
df = read_gmlc_gen(csv_path)

# path for the cost curves of fossil generators
# the calculation for the cost curve is in dispatches/improve_pt branch
json_path = os.path.join(os.getcwd(), '..', 'Data', 'rtsgmle_gen_linear_cost_curve.json')
with open(json_path, 'rb') as f:
    gen_param_dict = json.load(f)

# path for the buses
bus_path = os.path.join(os.getcwd(), "..", "Data", "bus.csv")
df_bus = pd.read_csv(bus_path)

In [15]:
# extract the CT, CC, STEAM, WIND, PV units
target_fossil_gen = []
target_renew_gen = []
target_special_gen = []
for idx, row in df.iterrows():
    if row['Unit Type'] in ['CT', 'CC', 'STEAM']:
        target_fossil_gen.append(row)
    if row['Unit Type'] in ['PV', 'WIND', 'HYDRO', 'RTPV']:
        target_renew_gen.append(row)
    if row['Unit Type'] in ['CSP', 'NUCLEAR']:
        target_special_gen.append(row)
df_fossil = pd.DataFrame(target_fossil_gen)
df_renew = pd.DataFrame(target_renew_gen)
df_special = pd.DataFrame(target_special_gen)

In [16]:
df_fossil.head()

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,Category,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,Emissions N2O Lbs/MMBTU,Emissions CO Lbs/MMBTU,Emissions VOCs Lbs/MMBTU,Damping Ratio,Inertia MJ/MW,Base MVA,Transformer X p.u.,Unit X p.u.,Pump Load MW,Storage Roundtrip Efficiency
0,101_CT_1,101,1,U20,CT,Oil CT,Oil,8.0,4.96,1.0468,...,0.004,0.11,0.040,0,2.8,24.0,0.13,0.32,0,0
1,101_CT_2,101,2,U20,CT,Oil CT,Oil,8.0,4.96,1.0468,...,0.004,0.11,0.040,0,2.8,24.0,0.13,0.32,0,0
2,101_STEAM_3,101,3,U76,STEAM,Coal,Coal,76.0,0.14,1.0468,...,0.004,0.02,0.003,0,3.0,89.0,0.13,0.30,0,0
3,101_STEAM_4,101,4,U76,STEAM,Coal,Coal,76.0,0.14,1.0468,...,0.004,0.02,0.003,0,3.0,89.0,0.13,0.30,0,0
4,102_CT_1,102,1,U20,CT,Oil CT,Oil,8.0,4.88,1.0467,...,0.004,0.11,0.040,0,2.8,24.0,0.13,0.32,0,0

In [17]:
df_renew.head()

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,Category,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,Emissions N2O Lbs/MMBTU,Emissions CO Lbs/MMBTU,Emissions VOCs Lbs/MMBTU,Damping Ratio,Inertia MJ/MW,Base MVA,Transformer X p.u.,Unit X p.u.,Pump Load MW,Storage Roundtrip Efficiency
74,122_HYDRO_1,122,1,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
75,122_HYDRO_2,122,2,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
76,122_HYDRO_3,122,3,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
77,122_HYDRO_4,122,4,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0
78,122_HYDRO_5,122,5,U50,HYDRO,Hydro,Hydro,50.0,-6.79,1.05,...,0.0,0.0,0.0,0,3.5,53.0,0.1,0.28,0,0

In [18]:
df_special

,GEN UID,Bus ID,Gen ID,Unit Group,Unit Type,Category,Fuel,MW Inj,MVAR Inj,V Setpoint p.u.,...,Emissions N2O Lbs/MMBTU,Emissions CO Lbs/MMBTU,Emissions VOCs Lbs/MMBTU,Damping Ratio,Inertia MJ/MW,Base MVA,Transformer X p.u.,Unit X p.u.,Pump Load MW,Storage Roundtrip Efficiency
73,121_NUCLEAR_1,121,1,U400,NUCLEAR,Nuclear,Nuclear,400.0,-21.87,1.05,...,0.0,0.0,0.0,0,5.0,471.0,0.15,0.4,0,0
116,212_CSP_1,212,1,CSP,CSP,CSP,Solar,0.0,0.00,1.00,...,0.0,0.0,0.0,0,0.0,200.0,0.00,0.0,0,0

## Calculate cost for the start up with different suitations

In [19]:
for idx, row in df_fossil.iterrows():
    fuel_price = row['Fuel Price $/MMBTU']
    cold_start_energy = row['Start Heat Cold MBTU']
    warm_start_energy = row['Start Heat Warm MBTU']
    hot_start_energy = row['Start Heat Hot MBTU']
    cold_start_cost = fuel_price * cold_start_energy
    warm_start_cost = fuel_price * warm_start_energy
    hot_start_cost =  fuel_price * hot_start_energy

In [20]:
df_bus.columns.tolist()

['Bus ID',
 'Bus Name',
 'BaseKV',
 'Bus Type',
 'MW Load',
 'MVAR Load',
 'V Mag',
 'V Angle',
 'MW Shunt G',
 'MVAR Shunt B',
 'Area',
 'Sub Area',
 'Zone',
 'lat',
 'lng']

In [21]:
# generate a dictionary contains fossil generator information
fossil_dict = {}
for idx, row in df_fossil.iterrows():
    gen_name = row['GEN UID']
    gen_dict = {}
    gen_dict['name'] = gen_name
    bus_id= row['Bus ID']
    gen_dict['bus_name'] = df_bus[df_bus["Bus ID"]==bus_id]["Bus Name"].to_list()[0]
    gen_dict['gen_type'] = row['Unit Type']
    gen_dict['max_p'] = row['PMax MW']
    gen_dict['min_p'] = row['PMin MW']
    gen_dict['ramp'] = row['Ramp Rate MW/Min'] * 60 # ramp rate should be MW/hr
    gen_dict['fuel_p'] = row['Fuel Price $/MMBTU']
    gen_dict['min_down_time'] = int(np.round(row['Min Down Time Hr'], 0)) # should be rounded to an integer
    gen_dict['min_up_time'] = int(np.round(row['Min Up Time Hr'], 0)) # should be rounded to an integer
    gen_dict['start_up_time_hot'] = int(np.round(row['Start Time Hot Hr'], 0))
    gen_dict['start_up_time_warm'] = int(np.round(row['Start Time Warm Hr'], 0))
    gen_dict['start_up_time_cold'] = int(np.round(row['Start Time Cold Hr'], 0))
    gen_dict['start_heat_hot'] = row['Start Heat Hot MBTU']
    gen_dict['start_heat_warm'] = row['Start Heat Warm MBTU']
    gen_dict['start_heat_cold'] = row['Start Heat Cold MBTU']
    gen_dict['cost_curve'] = gen_param_dict[gen_name]
    
    fossil_dict[gen_name] = gen_dict

In [22]:
# generate a dictionary contains renewable generator information
renew_dict = {}
for idx, row in df_renew.iterrows():
    gen_name = row['GEN UID']
    gen_dict = {}
    gen_dict['name'] = gen_name
    gen_dict['gen_type'] = row['Unit Type']
    bus_id= row['Bus ID']
    gen_dict['bus_name'] = df_bus[df_bus["Bus ID"]==bus_id]["Bus Name"].to_list()[0]
    gen_dict['max_p'] = row['PMax MW']
#     gen_dict['min_p'] = row['PMin MW']
#     gen_dict['ramp'] = row['Ramp Rate MW/Min']
#     gen_dict['min_down_time'] = row['Min Down Time Hr']
#     gen_dict['min_up_time'] = row['Min Up Time Hr']
#     gen_dict['start_up_time_hot'] = row['Start Time Hot Hr']
#     gen_dict['start_up_time_cold'] = row['Start Time Cold Hr']
#     gen_dict['start_up_time_cold'] = row['Start Time Warm Hr']
    gen_dict['cost_curve'] = {'slope': 0, 'intercept': 0} # for the renewable generators, the operation cost is 0.
    
    renew_dict[gen_name] = gen_dict

## Generator startup type check

In [16]:
# check the generator types to decide its startup types

# def gen_startup_cost(type_gen_dict, gen_name):
#     min_down_time = type_gen_dict[gen_name]['min_down_time']
#     hot_time = type_gen_dict[gen_name]['start_up_time_hot']
#     warm_time = type_gen_dict[gen_name]['start_up_time_warm']
#     cold_time = type_gen_dict[gen_name]['start_up_time_cold']
#     fuel_p = type_gen_dict[gen_name]['fuel_p']
#     start_heat_hot = type_gen_dict[gen_name]['start_heat_hot']
#     start_heat_warm = type_gen_dict[gen_name]['start_heat_warm']
#     start_heat_cold = type_gen_dict[gen_name]['start_heat_cold']
    
#     start_up_cost_hot = start_heat_hot*fuel_p
#     start_up_cost_warm = start_heat_warm*fuel_p
#     start_up_cost_cold = start_heat_cold*fuel_p
#     start_up_cost = {'hot': start_up_cost_hot, 'warm': start_up_cost_warm, 'cold': start_up_cost_cold}
    
#     return start_up_cost

## Save the gen_dict.json

In [25]:
all_gen_dict = {}
all_gen_dict['fossil'] = fossil_dict
all_gen_dict['renew'] = renew_dict
# all_gen_dict['special'] = special_dict

gen_dict_path = os.path.join(os.getcwd(), '..', 'Data', 'gen_dict.json')

with open(gen_dict_path, "w") as f:
     json.dump(all_gen_dict, f)
     print("Successfully saved generator parameters to json files")

Successfully saved generator parameters to json files

# ERCOT 123 Bus

## Read gen.csv

In [21]:
# path for the generators

csv_path = os.path.join(os.getcwd(), '..', '..', 'idaes-gtep', 'gtep', 'data', '123_Bus_Coal', 'gen.csv')
df = read_gmlc_gen(csv_path)

# # path for the cost curves of fossil generators
# json_path = os.path.join(os.getcwd(), '..', 'Data', 'rtsgmle_gen_linear_cost_curve.json')
# with open(json_path, 'rb') as f:
#     gen_param_dict = json.load(f)

# path for the buses
bus_path = os.path.join(os.getcwd(), '..', '..', 'idaes-gtep', 'gtep', 'data', '123_Bus_Coal', 'bus.csv')
df_bus = pd.read_csv(bus_path)

In [22]:
# extract the CT, CC, STEAM, WIND, PV units
target_fossil_gen = []
target_renew_gen = []
target_special_gen = []
for idx, row in df.iterrows():
    if row['Unit Type'] in ['CT', 'COAL']:
        target_fossil_gen.append(row)
    if row['Unit Type'] in ['PV', 'WIND', 'HYDRO']:
        target_renew_gen.append(row)
    if row['Unit Type'] in ['NUC']:
        target_special_gen.append(row)
        
df_fossil = pd.DataFrame(target_fossil_gen)
df_renew = pd.DataFrame(target_renew_gen)
df_special = pd.DataFrame(target_special_gen)

In [23]:
df_fossil.columns

Index(['GEN UID', 'Bus ID', 'Unit Type', 'Fuel', 'MW Inj', 'MVAR Inj',
       'V Setpoint p.u.', 'PMax MW', 'PMin MW', 'QMax MVAR', 'QMin MVAR',
       'Min Down Time Hr', 'Min Up Time Hr', 'Ramp Rate MW/Min',
       'Start Time Cold Hr', 'Start Time Warm Hr', 'Start Time Hot Hr',
       'Start Heat Cold MBTU', 'Start Heat Warm MBTU', 'Start Heat Hot MBTU',
       'Non Fuel Start Cost $', 'Fuel Price $/MMBTU', 'Output_pct_0',
       'Output_pct_1', 'Output_pct_2', 'Output_pct_3', 'Output_pct_4',
       'HR_avg_0', 'HR_incr_1', 'HR_incr_2', 'HR_incr_3', 'HR_incr_4',
       'capex1', 'capex2', 'capex3', 'fuel_cost1', 'fuel_cost2', 'fuel_cost3',
       'fixed_ops1', 'fixed_ops2', 'fixed_ops3', 'var_ops1', 'var_ops2',
       'var_ops3'],
      dtype='object')

In [24]:
# generate a dictionary contains fossil generator information
fossil_dict = {}
for idx, row in df_fossil.iterrows():
    gen_name = row['GEN UID'] + '_' + row['Unit Type']
    gen_dict = {}
    gen_dict['name'] = gen_name
    bus_id= row['Bus ID']
    gen_dict['bus_name'] = row['Bus ID']
    gen_dict['gen_type'] = row['Unit Type']
    gen_dict['max_p'] = row['PMax MW']
    gen_dict['min_p'] = row['PMin MW']
    gen_dict['ramp'] = row['PMax MW'] # no ramp rate, set to 100%/hr
#     gen_dict['fuel_p'] = row['Fuel Price $/MMBTU']
    gen_dict['min_down_time'] = int(np.round(row['Min Down Time Hr'], 0)) # should be rounded to an integer
    gen_dict['min_up_time'] = int(np.round(row['Min Up Time Hr'], 0)) # should be rounded to an integer
#     gen_dict['start_up_time_hot'] = int(np.round(row['Start Time Hot Hr'], 0))
#     gen_dict['start_up_time_warm'] = int(np.round(row['Start Time Warm Hr'], 0))
#     gen_dict['start_up_time_cold'] = int(np.round(row['Start Time Cold Hr'], 0))
#     gen_dict['start_heat_hot'] = row['Start Heat Hot MBTU']
#     gen_dict['start_heat_warm'] = row['Start Heat Warm MBTU']
#     gen_dict['start_heat_cold'] = row['Start Heat Cold MBTU']
#     gen_dict['cost_curve'] = gen_param_dict[gen_name]
    
    fossil_dict[gen_name] = gen_dict
    
fossil_dict.keys()

dict_keys(['2_CT', '3_CT', '4_CT', '5_CT', '6_COAL', '7_CT', '8_CT', '10_CT', '11_CT', '12_CT', '13_CT', '14_CT', '15_CT', '16_CT', '18_CT', '25_CT', '26_COAL', '27_CT', '28_CT', '44_CT', '45_CT', '47_CT', '48_CT', '49_CT', '50_CT', '51_CT', '54_CT', '60_CT', '61_CT', '62_CT', '66_CT', '70_CT', '71_CT', '72_CT', '73_CT', '75_CT', '76_CT', '85_CT', '94_CT', '98_CT', '100_CT', '105_CT', '107_CT', '108_CT', '112_CT', '114_CT', '118_CT', '121_CT', '122_CT', '124_CT', '129_CT', '130_CT', '137_CT', '138_CT', '144_CT', '147_CT', '148_CT', '149_CT', '150_CT', '151_CT', '155_CT', '156_CT', '165_COAL', '166_CT', '171_CT', '174_CT', '175_COAL', '176_CT', '177_COAL', '178_CT', '179_CT', '180_CT', '181_COAL', '182_CT', '183_CT', '184_CT', '185_COAL', '186_CT', '187_COAL', '189_CT', '193_CT', '195_CT', '197_CT', '201_CT', '202_CT', '203_CT', '207_CT', '208_CT', '209_CT', '211_CT', '212_CT', '213_CT', '215_CT', '216_CT', '220_CT', '222_CT', '223_CT', '224_CT', '226_CT', '227_CT', '228_CT', '229_CT', '230_CT', '231_CT', '232_COAL', '234_CT', '235_CT', '239_CT', '241_COAL', '242_CT', '243_CT', '244_CT', '246_CT', '250_COAL', '253_CT', '256_CT', '257_CT', '259_CT', '261_COAL', '262_CT', '263_CT', '264_CT', '268_CT', '269_COAL', '271_CT', '280_CT', 'ct_fe_1_1-c_CT', 'ct_fe_1_2-c_CT', 'ct_fe_1_3-c_CT', 'ct_fe_8_1-c_CT', 'ct_fe_8_2-c_CT', 'ct_fe_8_3-c_CT', 'ct_fe_15_1-c_CT', 'ct_fe_15_2-c_CT', 'ct_fe_15_3-c_CT', 'ct_fe_17_1-c_CT', 'ct_fe_17_2-c_CT', 'ct_fe_17_3-c_CT', 'ct_fe_18_1-c_CT', 'ct_fe_18_2-c_CT', 'ct_fe_18_3-c_CT', 'ct_fe_19_1-c_CT', 'ct_fe_19_2-c_CT', 'ct_fe_19_3-c_CT', 'ct_fe_23_1-c_CT', 'ct_fe_23_2-c_CT', 'ct_fe_23_3-c_CT', 'ct_fe_32_1-c_CT', 'ct_fe_32_2-c_CT', 'ct_fe_32_3-c_CT', 'ct_fe_33_1-c_CT', 'ct_fe_33_2-c_CT', 'ct_fe_33_3-c_CT', 'ct_fe_35_1-c_CT', 'ct_fe_35_2-c_CT', 'ct_fe_35_3-c_CT', 'ct_fe_36_1-c_CT', 'ct_fe_36_2-c_CT', 'ct_fe_36_3-c_CT', 'ct_fe_40_1-c_CT', 'ct_fe_40_2-c_CT', 'ct_fe_40_3-c_CT', 'ct_fe_42_1-c_CT', 'ct_fe_42_2-c_CT', 'ct_fe_42_3-c_CT', 'ct_fe_43_1-c_CT', 'ct_fe_43_2-c_CT', 'ct_fe_43_3-c_CT', 'ct_fe_44_1-c_CT', 'ct_fe_44_2-c_CT', 'ct_fe_44_3-c_CT', 'ct_fe_49_1-c_CT', 'ct_fe_49_2-c_CT', 'ct_fe_49_3-c_CT', 'ct_fe_54_1-c_CT', 'ct_fe_54_2-c_CT', 'ct_fe_54_3-c_CT', 'ct_fe_58_1-c_CT', 'ct_fe_58_2-c_CT', 'ct_fe_58_3-c_CT', 'ct_fe_61_1-c_CT', 'ct_fe_61_2-c_CT', 'ct_fe_61_3-c_CT', 'ct_fe_63_1-c_CT', 'ct_fe_63_2-c_CT', 'ct_fe_63_3-c_CT', 'ct_fe_65_1-c_CT', 'ct_fe_65_2-c_CT', 'ct_fe_65_3-c_CT', 'ct_fe_66_1-c_CT', 'ct_fe_66_2-c_CT', 'ct_fe_66_3-c_CT', 'ct_fe_74_1-c_CT', 'ct_fe_74_2-c_CT', 'ct_fe_74_3-c_CT', 'ct_fe_78_1-c_CT', 'ct_fe_78_2-c_CT', 'ct_fe_78_3-c_CT', 'ct_fe_79_1-c_CT', 'ct_fe_79_2-c_CT', 'ct_fe_79_3-c_CT', 'ct_fe_81_1-c_CT', 'ct_fe_81_2-c_CT', 'ct_fe_81_3-c_CT', 'ct_fe_90_1-c_CT', 'ct_fe_90_2-c_CT', 'ct_fe_90_3-c_CT', 'ct_fe_91_1-c_CT', 'ct_fe_91_2-c_CT', 'ct_fe_91_3-c_CT', 'ct_fe_93_1-c_CT', 'ct_fe_93_2-c_CT', 'ct_fe_93_3-c_CT', 'ct_fe_98_1-c_CT', 'ct_fe_98_2-c_CT', 'ct_fe_98_3-c_CT', 'ct_fe_99_1-c_CT', 'ct_fe_99_2-c_CT', 'ct_fe_99_3-c_CT', 'ct_fe_107_1-c_CT', 'ct_fe_107_2-c_CT', 'ct_fe_107_3-c_CT', 'ct_fe_110_1-c_CT', 'ct_fe_110_2-c_CT', 'ct_fe_110_3-c_CT', 'ct_fe_111_1-c_CT', 'ct_fe_111_2-c_CT', 'ct_fe_111_3-c_CT', 'ct_fe_112_1-c_CT', 'ct_fe_112_2-c_CT', 'ct_fe_112_3-c_CT', 'ct_fe_113_1-c_CT', 'ct_fe_113_2-c_CT', 'ct_fe_113_3-c_CT', 'ct_fe_115_1-c_CT', 'ct_fe_115_2-c_CT', 'ct_fe_115_3-c_CT', 'ct_fe_118_1-c_CT', 'ct_fe_118_2-c_CT', 'ct_fe_118_3-c_CT', 'ct_fe_120_1-c_CT', 'ct_fe_120_2-c_CT', 'ct_fe_120_3-c_CT'])

# Test Rolling Horizon PT codes

Need to checkout the branch of idaes-pse to "rolling_horizon"

## Test RHPTForecaster

In [1]:
from idaes.apps.grid_integration.forecaster import RHPTForecaster
import numpy as np

In [2]:
p = []
for i in range(10):
    p.append([i]*24)
price = np.array(p).reshape(-1)

scenario = 5
horizon = 36
planning_horizon = 24

In [3]:
forecaster = RHPTForecaster(price, scenario, horizon, planning_horizon)

pointer=0
forecaster._forecast_prices(pointer)

2025-07-02 15:48:13 [INFO] idaes.apps.grid_integration.forecaster: Number of periods from provided data is 10.
2025-07-02 15:48:13 [INFO] idaes.apps.grid_integration.forecaster: Number of scenarios is 5.
2025-07-02 15:48:13 [INFO] idaes.apps.grid_integration.forecaster: The length of the scenario is 36.

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
        8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
        9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
csv_path = "../Data/all_bus_lmp.csv"
df_lmp = pd.read_csv(csv_path)
lmp_arr = df_lmp['Abel_LMP'].to_numpy()
len(lmp_arr)

8784

In [8]:
forecaster = RHPTForecaster(lmp_arr, scenario, horizon, planning_horizon)

2025-07-02 15:48:25 [INFO] idaes.apps.grid_integration.forecaster: Number of periods from provided data is 366.
2025-07-02 15:48:25 [INFO] idaes.apps.grid_integration.forecaster: Number of scenarios is 5.
2025-07-02 15:48:25 [INFO] idaes.apps.grid_integration.forecaster: The length of the scenario is 36.

In [10]:
pointer = 7
lmp_forecasted = forecaster._forecast_prices(pointer)
for idx, l in enumerate(lmp_forecasted):
    actual_l = lmp_arr[(2+idx)*24: (2+idx)*24 + horizon]
    print(len(l), l- actual_l)

36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
36 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

## Test Rolling Horizon PT Results

In [33]:
from Customized_Determinstic_PT.utils import read_rolling_horizon_params, check_optimal_status, calculate_total_profit,calculate_total_startup_shutdown
# from Rolling_horizon.fossil_rolling_horizon_PT_parameter import gen_dict
# from idaes.apps.grid_integration import RHPTForecaster

In [32]:
# read the results dictionary
json_path = os.path.join(os.getcwd(), "..", "Data", "test_366_101_STEAM_3_result.json")
res_dict = read_rolling_horizon_params(json_path)

### Check if all period problem converged to optimal

In [30]:
non_optimal = check_optimal_status(res_dict)
print(non_optimal)

[]

### Compare the profit from PCM, PT and RHPT

In [31]:
actual_profit = calculate_total_profit(res_dict)
ideal_profit = calculate_total_profit(res_dict, name="IdeaProfit")

print(f"PCM Profit: {17.63} M$")
print(f"Standard Profit: {19.11} M$.")
print(f"Ideal Profit: {np.round(ideal_profit/1e6, 2)} M$.")
print(f"Actual Profit: {np.round(actual_profit/1e6, 2)} M$.")

PCM Profit: 17.63 M$
Standard Profit: 19.11 M$.
Ideal Profit: 16.96 M$.
Actual Profit: 14.66 M$.

### Compare the ideal and actual profit from RHPT

In [35]:
print("ideal", "actual")
for key in res_dict.keys():
    print(f"{np.round(res_dict[key]['IdeaProfit'], 2)}.", f"{np.round(res_dict[key]['ActualProfit'], 2)}.")

ideal actual
58311.6. -17108.49.
65379.29. -6068.05.
65447.93. -7794.03.
57795.8. 4857.58.
21257.66. -13649.83.
955.13. 13388.41.
-8993.15. 227.29.
5655.14. -16904.34.
4212.17. -11601.11.
1261.73. -7614.73.
2828.2. 2419.0.
-2602.7. 147650.05.
23765.99. 109230.09.
48471.16. -121.24.
50798.08. -7618.5.
50693.34. -12265.73.
47995.34. -431.27.
18368.18. -6204.83.
1205.68. 36863.78.
27799.13. 139152.48.
71577.96. 173866.7.
109702.21. 70484.27.
124305.16. -14735.88.
122522.83. -3614.56.
77736.01. -12467.8.
44033.97. -5744.03.
12157.03. -5973.94.
-12891.03. -17960.14.
-13244.82. -16239.33.
-14909.38. -15781.61.
-15387.22. -16347.35.
-15416.64. -16324.57.
27185.66. 31340.47.
57726.14. 152326.66.
103812.94. 133701.94.
134741.67. 164089.44.
170365.86. -914.58.
122317.27. 80765.42.
119339.31. 17772.63.
79127.99. 33656.67.
59146.2. 256925.87.
77732.88. 198268.26.
117599.6. -3178.99.
100659.23. 25306.03.
102195.57. 8422.4.
97148.71. -2764.94.
45210.55. -2134.85.
5133.31. 347331.77.
75274.87. 191967.61.
108807.68. 17254.24.
110422.57. -14582.68.
108078.41. -14882.39.
105650.41. 72225.39.
50671.1. -12967.2.
9990.98. 25172.44.
17222.01. 123615.36.
50151.35. 133149.06.
88523.1. 121660.42.
105308.25. 5692.84.
109830.81. 198618.02.
139262.9. -15261.43.
106812.7. -52.51.
72485.86. 73127.21.
55531.4. 185892.85.
91651.55. 67420.61.
65266.72. -3079.16.
67549.75. 224508.22.
115626.06. 8435.08.
103072.58. -18065.12.
62225.99. 30464.47.
54683.28. -12226.97.
53050.75. -1071.3.
4588.6. 53718.47.
14157.36. 717.95.
17476.53. 68857.38.
25008.1. -7257.63.
25990.56. 1508.05.
26458.52. -14778.19.
10463.86. 209748.0.
56208.08. 1590.95.
42970.68. 2426.42.
44903.47. 22152.05.
49062.32. 16271.03.
55120.68. 33113.55.
15345.28. 8147.59.
16503.96. 301522.94.
77514.29. 80877.64.
89361.42. 211230.7.
128329.72. -3491.74.
120976.3. 114064.83.
142132.48. 255156.83.
132020.93. 22963.16.
120189.04. -8358.78.
76249.52. 216973.7.
138321.71. 173495.15.
150283.31. 192218.08.
137501.53. 83310.29.
149948.38. 5338.16.
153264.06. 48134.4.
101201.35. 58869.48.
77841.14. -7852.82.
37216.37. 357961.15.
92192.86. 243941.8.
140508.6. -9136.8.
129317.21. -6525.25.
116268.19. 48781.82.
127374.9. -12559.61.
59886.52. -6449.71.
-7070.37. 35029.96.
16068.72. -28141.83.
12173.91. -17107.02.
-423.23. -4153.23.
929.41. 28767.11.
13674.93. 21890.65.
12307.28. 369850.87.
106727.0. 303780.5.
172919.15. 422775.28.
258101.05. 292013.3.
303415.12. 159557.91.
326081.43. -7363.93.
236241.1. 10879.7.
176618.8. 10815.28.
93696.65. 42106.38.
44029.25. 51200.67.
22552.06. 130674.97.
49272.22. 133620.54.
84611.31. -1679.56.
82081.48. -10163.96.
71325.66. 89339.63.
79044.94. 266485.8.
106819.87. 57986.32.
82212.58. -14949.23.
78995.96. 1379.84.
80547.29. -154.54.
62443.89. 98571.21.
29781.95. -4160.33.
17849.58. 1802.92.
20653.33. 773.34.
20352.38. 5348.15.
21652.78. 4074.1.
2358.11. 4521.16.
3884.3. 24654.24.
8110.74. 5796.17.
9590.7. -6185.02.
6954.52. 4750.49.
6983.71. 1693.78.
6624.66. -16587.96.
0.0. 0.0.
11138.31. 16767.13.
28706.99. 80026.94.
65085.87. -5159.45.
64143.09. -22230.48.
63297.96. -19823.03.
35133.85. 46873.22.
44136.34. 99843.51.
32284.27. 16495.88.
35164.43. 81378.46.
55206.55. -5741.39.
57886.2. 18726.26.
48054.01. -1676.62.
23088.71. 16215.17.
22562.58. 7643.84.
7351.42. -8534.48.
6667.08. 85112.62.
19863.62. 85075.08.
37181.6. -300.59.
33980.39. 4190.88.
33588.37. 9862.08.
36960.06. 53674.56.
31174.86. 65645.62.
27597.68. -6382.91.
26427.77. -2437.3.
24718.0. 81999.35.
39223.04. 184169.5.
64762.6. 13235.1.
54362.01. 6003.41.
57370.59. 43120.1.
66678.73. 46777.71.
59741.51. 6566.15.
23825.58. 6866.93.
22186.53. 27330.46.
26204.66. 7948.39.
19097.93. -5799.29.
8600.3. 4725.22.
8303.54. 6528.45.
8240.49. 4668.85.
3762.58. 4691.67.
3195.9. 3631.34.
5061.81. -1235.81.
3910.02. 84189.32.
19498.82. 111114.84.
40816.28. 5410.3.
40943.41. 4952.17.
41145.59. 49741.6.
51341.08. 85868.88.
51576.7. 53682.05.
39967.37. 21885.54.
43226.05. 15294.25.
45294.46. 6977.09.
36741.56. 42773.61.
28122.51. 17463.77.
20878.85. 17487.81.
19999.31. 8386.41.
18617.74. 9048.79.
19032.08. 8934.9.
12264.34. 8587.15.
10489.01. 7715.71.
8534.59. 16611.38.
10179.59. 15578.38.
11485.5. 7540.27.
11206.58. 8669.34.
11223.02. 16721.63.
13024.2. 4285.91.
10559.11. 4741.28.
8391.69. -13008.07.
4282.02. 5346.47.
3617.44. 3556.52.
984.42. 7862.65.
1699.77. 10592.69.
2870.05. 8655.69.
7202.81. 6162.63.
7366.04. 4099.37.
7474.61. 6454.07.
7192.89. 16818.84.
8438.12. 4110.93.
7529.17. 14979.35.
9292.52. 6184.36.
9709.51. 4572.91.
9333.28. 5326.86.
7034.88. 16554.46.
9523.59. 3069.34.
7141.59. 44562.81.
14817.28. 15184.76.
16939.65. 5623.34.
16998.94. 5516.39.
14791.33. 4421.15.
15061.69. 15179.35.
9185.0. 185567.96.
43261.64. 22003.36.
46537.64. 7781.22.
46990.61. 6338.35.
47374.05. 4196.49.
45177.48. -768.34.
7922.01. 52206.82.
14007.06. 33419.27.
19559.61. 921.66.
18630.39. 6960.06.
19287.67. 3060.91.
19599.06. 5312.14.
10328.19. 3501.46.
4133.94. 4026.65.
4727.49. 7024.75.
4479.24. 7445.53.
5327.79. 4948.47.
5141.96. 12377.77.
7241.12. 3238.25.
7006.95. 5273.08.
6656.62. 4891.71.
6145.86. 114695.81.
28095.32. 45978.96.
34818.19. -7567.69.
32671.34. -7433.86.
30136.77. -24693.14.
25375.35. -3195.09.
8026.91. 219.41.
-13901.93. 58587.48.
22793.03. -14526.06.
20822.71. 1020.31.
24753.51. 10500.54.
27456.27. 352.38.
23848.25. -1730.57.
-656.05. 2110.79.
2671.29. 3798.52.
3918.29. 4009.24.
2380.86. 3676.28.
3056.95. 4837.9.
4992.67. -1641.69.
3840.9. -768.74.
2654.41. 2156.83.
2218.07. 4757.7.
2335.91. 1434.19.
1622.73. -7966.8.
152.63. -948.73.
69.0. -12941.29.
124.9. 13.07.
-11727.21. -10832.58.
-11905.82. -10873.0.
-11771.09. -10272.37.
-11623.93. -9691.19.
-10677.62. -10371.55.
-10408.14. -11965.78.
-10634.78. -19970.65.
-12454.31. 28438.71.
10759.84. -11162.64.
22477.45. 145586.88.
60246.78. 80922.72.
80132.13. 76661.78.
100961.56. 4538.68.
73124.02. 7448.82.
74314.47. -2144.27.
35271.52. -69.22.
17902.21. 37673.85.
10152.16. -22365.19.
4964.61. 27287.83.
15830.56. -8875.65.
29385.25. -290.96.
47230.19. -2093.02.
39148.82. 412.17.
43188.46. 95227.1.
57142.88. 419336.56.
127446.11. 262654.43.
175703.2. -25282.46.
170882.37. -25364.12.
165325.47. 10590.54.
148416.15. -12643.87.
44502.04. 194329.1.
30313.03. 87344.49.
52363.45. 78685.16.
77142.49. 122642.41.
99391.9. -22315.11.
97003.19. -9729.14.
56322.64. 35535.43.
52264.74. 6482.16.
20708.69. -22299.17.
6956.31. 443.85.
11072.03. 230032.98.
58473.2. 157759.68.
89656.29. 76302.6.
99123.74. 135034.07.
127828.39. -15997.81.
124253.15. -7119.49.
77206.4. -28526.59.
38134.73. -9065.9.
10125.41. -11886.78.
-15905.43. -16519.19.
-15984.01. -16618.85.
-15887.21. -11136.79.
-16585.44. 5967.45.
2046.09. 237190.64.
64951.61. 10377.49.
72562.98. 56227.73.
81402.25. 37574.75.
88379.14. -4839.18.
81976.83. 1420.34.
20227.22. 283127.84.
74702.3. -5716.32.
62433.05. -6143.16.
53764.46. 156931.91.
86748.3. 28622.33.
92188.69. -20935.49.
36552.45. -815.81.
20232.5. 62331.42.
47961.96. 200613.82.
60547.64. -9104.38.
53437.03. 9245.51.
58888.99. 2639.12.
61969.97. 308.27.
46142.03. 224661.2.
46617.2. 68233.24.
62645.66. -8750.32.
58675.63. 63269.21.
70718.43. 14786.36.
73335.17. -6450.71.
27033.89. 31578.04.
19190.17. 185526.81.
58707.58. 117512.4.

### Find out startup and shutdown time

In [37]:
for key in res_dict.keys():
    total_shutdown = sum(res_dict[key]["101_STEAM_3"]["OperationVariables_shutdown"]["1"].values())
    total_startup = sum(res_dict[key]["101_STEAM_3"]["OperationVariables_startup"]["1"].values())
    if total_shutdown > 0:
        print("shutdown", key)
    if total_startup > 0:
        print("startup", key)

startup period_0
shutdown period_5
startup period_6
shutdown period_18
startup period_19
shutdown period_26
shutdown period_27
startup period_27
shutdown period_28
startup period_28
shutdown period_29
startup period_29
shutdown period_30
startup period_30
shutdown period_31
startup period_31
startup period_32
shutdown period_107
startup period_108
shutdown period_147
startup period_148
shutdown period_264
startup period_265
shutdown period_284
shutdown period_285
startup period_285
shutdown period_286
startup period_286
shutdown period_287
startup period_287
shutdown period_288
startup period_288
shutdown period_289
startup period_289
shutdown period_290
startup period_290
shutdown period_291
startup period_291
shutdown period_292
startup period_292
startup period_293
shutdown period_304
startup period_305
shutdown period_322
startup period_323
shutdown period_332
shutdown period_333
startup period_333
shutdown period_334
startup period_334
shutdown period_335
startup period_335
shutdown period_336
startup period_336
startup period_337
shutdown period_350
startup period_351

In [39]:
calculate_total_startup_shutdown(res_dict, gen_name="101_STEAM_3")

(29.0, 28.0)

### Verify

In [49]:
slope = 16.466, 
intercept = 331.4380855711627

lmp_path = os.path.join("..", "Data", "all_bus_lmp.csv")
df_lmp = pd.read_csv(lmp_path)
lmp_data = df_lmp[gen_dict["gen_101_STEAM_3"]["bus_name"]+"_LMP"].to_numpy()

forecaster = RHPTForecaster(price_signal=lmp_data,
                            scenario=5,
                            horizon=36,
                            planning_horizon=24)

elec_rev = 0
cost = 0
pointer = 0

for i in res_dict:
    power =  res_dict[i]['gen_101_STEAM_3']['OperationVariables_power']['1']
    op_mode = res_dict[i]['gen_101_STEAM_3']['OperationVariables_op_mode']['1']
    power_arr = np.array([v for v in power.values()])
    op_mode_arr = np.array([v for v in op_mode.values()])
    lmp = forecaster.fetch_original_signal(pointer)
    cost += sum(power_arr * slope + op_mode_arr * intercept)
    elec_rev += sum(lmp*power_arr)
    pointer += 1
    
cost += 29*5284.8*2.11399

elec_rev, cost, elec_rev-cost

2025-08-15 00:26:07 [INFO] idaes.apps.grid_integration.forecaster: Number of periods from provided data is 366.
2025-08-15 00:26:07 [INFO] idaes.apps.grid_integration.forecaster: Number of scenarios is 5.
2025-08-15 00:26:07 [INFO] idaes.apps.grid_integration.forecaster: The length of the scenario is 36.

(26816963.368243992, 11831442.209015777, 14985521.159228215)

## Using new LMP

### PCM

In [32]:
df_lmp = pd.read_csv("Bus_LMP.csv")
df_dispatch = pd.read_csv("Generator_Dispatch.csv")

state_arr = df_dispatch["101_STEAM_3_Unit State"].to_numpy()

int_state_arr = []
for i in state_arr:
    if i:
        int_state_arr.append(1)
    else:
        int_state_arr.append(0)
int_state_arr = np.array(int_state_arr)

startups = 0
for i in range(1, len(state_arr)):
    if int(state_arr[i]) - int(state_arr[i-1]) == 1:
        startups += 1
        
dispatch_arr = df_dispatch["101_STEAM_3_Dispatch"].to_numpy()

costs = dispatch_arr * 16.466 + 331.4381*int_state_arr
sum(costs) + 2.11399*5284.8*6

# sum(df_lmp["Abel_LMP"].to_numpy() * dispatch_arr)

12467569.950188339

### Determinstic PT (fixed dispatch)

In [33]:
js_path = "../Data/det_fossil_PT_fixed_dispatch_results.json"

with open(js_path, "r") as f:
    res_dict = json.load(f)

startup = 0
rev = 0
vom = 0
for i in range(1, 366*24):
    startup += res_dict[str(i)]['startup']
    rev += res_dict[str(i)]['rev']
    vom += res_dict[str(i)]['vom']
    
startup, rev, vom + 2.11399*5284.8*6

(7.0, 29073470.33426585, 12465986.972160637)

### Determinstic PT (unfixed dispatch)

In [34]:
js_path = "../Data/det_fossil_PT_unfixed_dispatch_results.json"

with open(js_path, "r") as f:
    res_dict = json.load(f)

startup = 0
rev = 0
vom = 0
for i in range(1, 366*24):
    startup += res_dict[str(i)]['startup']
    rev += res_dict[str(i)]['rev']
    vom += res_dict[str(i)]['vom']
    
startup, rev, vom + 2.11399*5284.8*(startup-1)

(58.0, 28308104.85466783, 10165112.741302129)